In [1]:
import tensorflow as tf


In [2]:
images = tf.constant([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]
])

labels = tf.constant([0, 1, 1])

In [3]:
dataset = tf.data.Dataset.from_tensor_slices((images, labels))
for elements in dataset:
  for element in elements:
    print(element.numpy())
  

[1 2 3]
0
[4 5 6]
1
[7 8 9]
1


In [4]:
dataset = dataset.shuffle(buffer_size=3).batch(2)


In [5]:
first_batch = dataset.take(1)
for elements in first_batch:
  for element in elements:
    print('first batch: ', element.numpy())
  

first batch:  [[4 5 6]
 [1 2 3]]
first batch:  [1 0]


In [6]:
dataset = dataset.repeat(3)
for elements in dataset:
  for element in elements:
    print('repeated_ds: ', element.numpy())

repeated_ds:  [[4 5 6]
 [1 2 3]]
repeated_ds:  [1 0]
repeated_ds:  [[7 8 9]]
repeated_ds:  [1]
repeated_ds:  [[7 8 9]
 [4 5 6]]
repeated_ds:  [1 1]
repeated_ds:  [[1 2 3]]
repeated_ds:  [0]
repeated_ds:  [[1 2 3]
 [7 8 9]]
repeated_ds:  [0 1]
repeated_ds:  [[4 5 6]]
repeated_ds:  [1]


In [7]:
extra_labels = tf.constant([2, 5, 8])
extra_dataset = tf.data.Dataset.from_tensor_slices(extra_labels)

zipped_dataset = tf.data.Dataset.zip((dataset, extra_dataset))


In [9]:
taken_dataset = zipped_dataset.take(5)
for elements in taken_dataset:
  for element in elements:
    print('repeated_ds: ', element)
    

repeated_ds:  (<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [7, 8, 9]], dtype=int32)>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>)
repeated_ds:  tf.Tensor(2, shape=(), dtype=int32)
repeated_ds:  (<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]], dtype=int32)>, <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>)
repeated_ds:  tf.Tensor(5, shape=(), dtype=int32)
repeated_ds:  (<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[4, 5, 6],
       [7, 8, 9]], dtype=int32)>, <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1], dtype=int32)>)
repeated_ds:  tf.Tensor(8, shape=(), dtype=int32)


In [10]:
cached_dataset = taken_dataset.cache()

In [11]:
prefetch_dataset = cached_dataset.prefetch(tf.data.experimental.AUTOTUNE)

In [13]:
for element in prefetch_dataset:
  (image, label), extra_lable = element
  print('image: ', image.numpy())
  print('label: ', label.numpy())
  print('extra_lable', extra_lable.numpy())

  

image:  [[4 5 6]
 [7 8 9]]
label:  [1 1]
extra_lable 2
image:  [[1 2 3]]
label:  [0]
extra_lable 5
image:  [[1 2 3]
 [4 5 6]]
label:  [0 1]
extra_lable 8


In [ ]:
#end