In [ ]:
import torch

In [ ]:
x = torch.rand(5, 3, 5, 5)
print(x)


tensor([[[[0.7110, 0.7347, 0.3689, 0.8369, 0.8977],
          [0.9908, 0.6191, 0.0976, 0.4059, 0.4227],
          [0.1187, 0.7784, 0.2726, 0.4149, 0.0417],
          [0.4327, 0.9977, 0.0827, 0.4617, 0.3489],
          [0.4074, 0.8128, 0.8034, 0.9000, 0.9184]],

         [[0.4413, 0.6005, 0.1940, 0.5834, 0.7999],
          [0.7957, 0.3291, 0.9398, 0.5721, 0.3131],
          [0.8699, 0.4611, 0.6710, 0.5060, 0.1844],
          [0.1105, 0.4110, 0.0327, 0.6050, 0.9071],
          [0.3634, 0.0482, 0.7059, 0.0559, 0.4290]],

         [[0.1079, 0.4513, 0.8694, 0.3019, 0.2697],
          [0.0944, 0.7270, 0.6721, 0.7763, 0.0889],
          [0.9868, 0.6447, 0.3902, 0.1841, 0.5907],
          [0.1276, 0.1023, 0.5414, 0.2533, 0.9340],
          [0.5763, 0.4286, 0.9802, 0.6748, 0.2220]]],


        [[[0.1354, 0.8796, 0.3810, 0.8336, 0.8860],
          [0.4937, 0.4558, 0.2170, 0.7609, 0.4358],
          [0.0812, 0.6422, 0.4866, 0.1726, 0.8529],
          [0.0154, 0.5077, 0.1346, 0.2955, 0.0450],
    

In [ ]:
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x.size()

torch.Size([5, 3])

In [ ]:
x.dtype

torch.float32

In [ ]:
x = torch.zeros(5, 3, dtype=torch.float32)
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
x = torch.tensor([12.3, 4])
x

tensor([12.3000,  4.0000])

In [ ]:
y = torch.rand(5, 5)
z = torch.rand(5, 5)

print(y)
print(z)

tensor([[0.2832, 0.4978, 0.5754, 0.7247, 0.9284],
        [0.6844, 0.8560, 0.1836, 0.0947, 0.0146],
        [0.4148, 0.6254, 0.8024, 0.6198, 0.3121],
        [0.3093, 0.9000, 0.6257, 0.5976, 0.5295],
        [0.5751, 0.5720, 0.0405, 0.4678, 0.5439]])
tensor([[0.4641, 0.6894, 0.1469, 0.9342, 0.6150],
        [0.4815, 0.7977, 0.2057, 0.3991, 0.0927],
        [0.5843, 0.1619, 0.2235, 0.9189, 0.8094],
        [0.0131, 0.4476, 0.8338, 0.7914, 0.0889],
        [0.5525, 0.7002, 0.1441, 0.0681, 0.5183]])


In [ ]:
sum = y + z
print(sum)

tensor([[0.7473, 1.1872, 0.7223, 1.6589, 1.5434],
        [1.1659, 1.6537, 0.3892, 0.4938, 0.1074],
        [0.9990, 0.7873, 1.0259, 1.5387, 1.1215],
        [0.3224, 1.3475, 1.4594, 1.3890, 0.6184],
        [1.1276, 1.2723, 0.1846, 0.5359, 1.0622]])


In [ ]:
sum = torch.add(y, z)
print(sum)

tensor([[0.7473, 1.1872, 0.7223, 1.6589, 1.5434],
        [1.1659, 1.6537, 0.3892, 0.4938, 0.1074],
        [0.9990, 0.7873, 1.0259, 1.5387, 1.1215],
        [0.3224, 1.3475, 1.4594, 1.3890, 0.6184],
        [1.1276, 1.2723, 0.1846, 0.5359, 1.0622]])


In [ ]:
z.add_(y)
print(z)

tensor([[0.7473, 1.1872, 0.7223, 1.6589, 1.5434],
        [1.1659, 1.6537, 0.3892, 0.4938, 0.1074],
        [0.9990, 0.7873, 1.0259, 1.5387, 1.1215],
        [0.3224, 1.3475, 1.4594, 1.3890, 0.6184],
        [1.1276, 1.2723, 0.1846, 0.5359, 1.0622]])


In [ ]:
sub = z - y
print(sub)

tensor([[0.4641, 0.6894, 0.1469, 0.9342, 0.6150],
        [0.4815, 0.7977, 0.2057, 0.3991, 0.0927],
        [0.5843, 0.1619, 0.2235, 0.9189, 0.8094],
        [0.0131, 0.4476, 0.8338, 0.7914, 0.0889],
        [0.5525, 0.7002, 0.1441, 0.0681, 0.5183]])


In [ ]:
sub = torch.sub(z, y)
print(sub)

tensor([[0.4641, 0.6894, 0.1469, 0.9342, 0.6150],
        [0.4815, 0.7977, 0.2057, 0.3991, 0.0927],
        [0.5843, 0.1619, 0.2235, 0.9189, 0.8094],
        [0.0131, 0.4476, 0.8338, 0.7914, 0.0889],
        [0.5525, 0.7002, 0.1441, 0.0681, 0.5183]])


In [ ]:
mult = z * y
print(mult)

tensor([[0.2116, 0.5910, 0.4156, 1.2022, 1.4328],
        [0.7979, 1.4156, 0.0714, 0.0468, 0.0016],
        [0.4144, 0.4924, 0.8232, 0.9537, 0.3500],
        [0.0997, 1.2128, 0.9132, 0.8301, 0.3275],
        [0.6484, 0.7278, 0.0075, 0.2507, 0.5777]])


In [ ]:
mult = torch.mul(z, y)
print(mult)

tensor([[0.2116, 0.5910, 0.4156, 1.2022, 1.4328],
        [0.7979, 1.4156, 0.0714, 0.0468, 0.0016],
        [0.4144, 0.4924, 0.8232, 0.9537, 0.3500],
        [0.0997, 1.2128, 0.9132, 0.8301, 0.3275],
        [0.6484, 0.7278, 0.0075, 0.2507, 0.5777]])


In [ ]:
divi = z / y
print(divi)

tensor([[2.6389, 2.3850, 1.2553, 2.2891, 1.6624],
        [1.7035, 1.9319, 2.1205, 5.2136, 7.3358],
        [2.4087, 1.2589, 1.2785, 2.4826, 3.5937],
        [1.0424, 1.4973, 2.3326, 2.3242, 1.1679],
        [1.9607, 2.2241, 4.5558, 1.1456, 1.9529]])


In [ ]:
divi = torch.div(z, y)
print(divi)

tensor([[2.6389, 2.3850, 1.2553, 2.2891, 1.6624],
        [1.7035, 1.9319, 2.1205, 5.2136, 7.3358],
        [2.4087, 1.2589, 1.2785, 2.4826, 3.5937],
        [1.0424, 1.4973, 2.3326, 2.3242, 1.1679],
        [1.9607, 2.2241, 4.5558, 1.1456, 1.9529]])


In [ ]:
slc = torch.rand(12, 4)
print(slc)

tensor([[0.5805, 0.9891, 0.1509, 0.8907],
        [0.6779, 0.8081, 0.6475, 0.8240],
        [0.1897, 0.9905, 0.3764, 0.1767],
        [0.3728, 0.0482, 0.7595, 0.6986],
        [0.9817, 0.4013, 0.8280, 0.3815],
        [0.9735, 0.8232, 0.9330, 0.8685],
        [0.6381, 0.1611, 0.1283, 0.8766],
        [0.3169, 0.1873, 0.4024, 0.7030],
        [0.0518, 0.3628, 0.8717, 0.3832],
        [0.0115, 0.6131, 0.5985, 0.9495],
        [0.9800, 0.1512, 0.1532, 0.3537],
        [0.1121, 0.3816, 0.6637, 0.9962]])


In [ ]:
slc[:, 0]

tensor([0.5805, 0.6779, 0.1897, 0.3728, 0.9817, 0.9735, 0.6381, 0.3169, 0.0518,
        0.0115, 0.9800, 0.1121])

In [ ]:
slc[2, :]

tensor([0.1897, 0.9905, 0.3764, 0.1767])

In [ ]:
slc[5, 3].item()

0.8684630393981934

In [ ]:
t = torch.rand(3, 4)
t_reshaped = t.view(12)
print(t_reshaped)

tensor([0.0896, 0.3242, 0.8015, 0.5895, 0.0237, 0.1886, 0.6879, 0.3853, 0.8992,
        0.1678, 0.3476, 0.5253])


In [ ]:
t_r = t.view(-1, 3)
t_r

tensor([[0.0896, 0.3242, 0.8015],
        [0.5895, 0.0237, 0.1886],
        [0.6879, 0.3853, 0.8992],
        [0.1678, 0.3476, 0.5253]])

In [ ]:
t_r.size()

torch.Size([4, 3])

In [ ]:
# array ---> Numpy, Tensor ---> Pytorch
c = torch.ones(5)
c.type

d = c.numpy()
print(d)
print(type(d))

f = torch.from_numpy(d)
print(f)
print(f.type)


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.])
<built-in method type of Tensor object at 0x7f47688fa7f0>


In [ ]:
x= torch.tensor(2.0, requires_grad=True)
y = x**3 + 1

y.backward()
dy_dx = x.grad

print(dy_dx)

tensor(12.)


In [ ]:
x = torch.tensor(5.0)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

o = w*x + b

o.backward()

do_dx = x.grad
do_dw = w.grad
do_db = b.grad
print(do_dx)
print(do_dw)
print(do_db)

None
tensor(5.)
tensor(1.)


In [ ]:
#x = torch.tensor(5.0)
w = torch.tensor(3.0, requires_grad=True)
b = torch.tensor(1.0, requires_grad=True)

f = w + b
g = w + 5

y = torch.mul(f, g)


y.backward()
dy_dw = w.grad
print(dy_dw)



tensor(12.)


In [ ]:
x = torch.tensor(3.0)
w1 = torch.tensor(1.0, requires_grad=True)
w2 = torch.tensor(2.0, requires_grad=True)
w3 = torch.tensor(4.0, requires_grad=True)

net = w1 * x
out = 2 * net

y1_pred = w2 * out
y2_pred = w3 * out

y1_pred.backward(retain_graph=True) # fine
y2_pred.backward(retain_graph=True) # fine

loss = y1_pred + y2_pred

#loss = 0.5 *( (3-y1_pred)**2  + (1-y2_pred)**2 )

#loss.backward()

dloss_dw1 = w1.grad
print(dloss_dw1)

tensor(36.)


In [ ]:
import torch
from torch.autograd import Variable
a = Variable(torch.rand(1, 4), requires_grad=True)
b = a**2
c = b*2
d = c.mean()
e = c.sum()

d.backward(retain_graph=True) # fine
e.backward(retain_graph=True) # fine

ff = a.grad

# dd_da + de_da
print(ff)

tensor([[4.1966, 3.3268, 1.7188, 0.1805]])
